language: node_js
node_js:
    - stable

addons:
  postgresql: "9.4"

before_install:
    - npm install -g gulp esdoc mocha
    - chmod 755 ./deploy_docs.sh
    - psql -c 'create database ninja_db;' -U postgres
    - psql -U postgres -d ninja_db -a -f ./schema/schema.sql
    - psql -U postgres -d ninja_db -a -f ./schema/data.sql

script:
    - gulp
    - npm run travis
    - npm test

after_success:
    - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
    - bash ./deploy_docs.sh

env:
  global:
  - GH_REF: github.com/The-United-States-Of-America/ninja-backend-dbsrv.git

notifications:
  slack: team-murica:KwaWUHr5gCRzm33eJuJUvAsu
