language: node_js
node_js:
    - stable

addons:
  postgresql: "9.4"

before_install:
    - npm install -g gulp esdoc mocha
    - chmod 755 ./deploy_docs.sh

script:
    - gulp
    - bash ./deploy_docs.sh

env:
  global:
  - GH_REF: github.com/The-United-States-Of-America/ninja-backend-dbsrv.git
