window.esdocSearchIndex = [
  [
    "ninja-backend-dbsrv/src/models/administrator.js~administrator",
    "class/src/models/administrator.js~Administrator.html",
    "<span>Administrator</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/administrator.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/administrator.js~administratorroute",
    "class/src/routes/administrator.js~AdministratorRoute.html",
    "<span>AdministratorRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/administrator.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/appointments.js~appointmentroute",
    "class/src/routes/appointments.js~AppointmentRoute.html",
    "<span>AppointmentRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/appointments.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/appointments.js~appointmentsroute",
    "class/src/models/appointments.js~AppointmentsRoute.html",
    "<span>AppointmentsRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/appointments.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/client.js~client",
    "class/src/models/client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/client.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/client.js~clientroute",
    "class/src/routes/client.js~ClientRoute.html",
    "<span>ClientRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/client.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/family.js~family",
    "class/src/models/family.js~Family.html",
    "<span>Family</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/family.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/familyrequests.js~familyrequests",
    "class/src/models/familyrequests.js~FamilyRequests.html",
    "<span>FamilyRequests</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/familyrequests.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/family.js~familyroute",
    "class/src/routes/family.js~FamilyRoute.html",
    "<span>FamilyRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/family.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/file.js~fileroute",
    "class/src/routes/file.js~FileRoute.html",
    "<span>FileRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/file.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~madministrator",
    "variable/index.html#static-variable-MAdministrator",
    "<span>MAdministrator</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mappointments",
    "variable/index.html#static-variable-MAppointments",
    "<span>MAppointments</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mclient",
    "variable/index.html#static-variable-MClient",
    "<span>MClient</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mfamily",
    "variable/index.html#static-variable-MFamily",
    "<span>MFamily</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mfamilyrequests",
    "variable/index.html#static-variable-MFamilyRequests",
    "<span>MFamilyRequests</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~morganization",
    "variable/index.html#static-variable-MOrganization",
    "<span>MOrganization</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~morganizationrequests",
    "variable/index.html#static-variable-MOrganizationRequests",
    "<span>MOrganizationRequests</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mprovider",
    "variable/index.html#static-variable-MProvider",
    "<span>MProvider</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~mtaxonomy",
    "variable/index.html#static-variable-MTaxonomy",
    "<span>MTaxonomy</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/models.js~muser",
    "variable/index.html#static-variable-MUser",
    "<span>MUser</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/models.js</span>",
    "variable"
  ],
  [
    "ninja-backend-dbsrv/src/models/organization.js~organization",
    "class/src/models/organization.js~Organization.html",
    "<span>Organization</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/organization.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/organizationrequests.js~organizationrequests",
    "class/src/models/organizationrequests.js~OrganizationRequests.html",
    "<span>OrganizationRequests</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/organizationrequests.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/organization.js~organizationroute",
    "class/src/routes/organization.js~OrganizationRoute.html",
    "<span>OrganizationRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/organization.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/provider.js~provider",
    "class/src/models/provider.js~Provider.html",
    "<span>Provider</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/provider.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/routes/provider.js~providerroute",
    "class/src/routes/provider.js~ProviderRoute.html",
    "<span>ProviderRoute</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/routes/provider.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/router.js~router",
    "class/src/Router.js~Router.html",
    "<span>Router</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/Router.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/user.js~user",
    "class/src/models/user.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/user.js</span>",
    "class"
  ],
  [
    "ninja-backend-dbsrv/src/models/user.js~usertypes",
    "variable/index.html#static-variable-UserTypes",
    "<span>UserTypes</span> <span class=\"search-result-import-path\">ninja-backend-dbsrv/src/models/user.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/database.js",
    "file/src/Database.js.html",
    "src/Database.js",
    "file"
  ],
  [
    "src/router.js",
    "file/src/Router.js.html",
    "src/Router.js",
    "file"
  ],
  [
    "src/router.js~router#constructor",
    "class/src/Router.js~Router.html#instance-constructor-constructor",
    "src/Router.js~Router#constructor",
    "method"
  ],
  [
    "src/app.js",
    "file/src/app.js.html",
    "src/app.js",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/models/administrator.js",
    "file/src/models/administrator.js.html",
    "src/models/administrator.js",
    "file"
  ],
  [
    "src/models/administrator.js~administrator.create",
    "class/src/models/administrator.js~Administrator.html#static-method-create",
    "src/models/administrator.js~Administrator.create",
    "method"
  ],
  [
    "src/models/administrator.js~administrator.get",
    "class/src/models/administrator.js~Administrator.html#static-method-get",
    "src/models/administrator.js~Administrator.get",
    "method"
  ],
  [
    "src/models/administrator.js~administrator.joinorganization",
    "class/src/models/administrator.js~Administrator.html#static-method-joinOrganization",
    "src/models/administrator.js~Administrator.joinOrganization",
    "method"
  ],
  [
    "src/models/appointments.js",
    "file/src/models/appointments.js.html",
    "src/models/appointments.js",
    "file"
  ],
  [
    "src/models/appointments.js~appointmentsroute.client_appointments",
    "class/src/models/appointments.js~AppointmentsRoute.html#static-method-client_appointments",
    "src/models/appointments.js~AppointmentsRoute.client_appointments",
    "method"
  ],
  [
    "src/models/appointments.js~appointmentsroute.create",
    "class/src/models/appointments.js~AppointmentsRoute.html#static-method-create",
    "src/models/appointments.js~AppointmentsRoute.create",
    "method"
  ],
  [
    "src/models/appointments.js~appointmentsroute.provider_appointments",
    "class/src/models/appointments.js~AppointmentsRoute.html#static-method-provider_appointments",
    "src/models/appointments.js~AppointmentsRoute.provider_appointments",
    "method"
  ],
  [
    "src/models/appointments.js~appointmentsroute.update",
    "class/src/models/appointments.js~AppointmentsRoute.html#static-method-update",
    "src/models/appointments.js~AppointmentsRoute.update",
    "method"
  ],
  [
    "src/models/client.js",
    "file/src/models/client.js.html",
    "src/models/client.js",
    "file"
  ],
  [
    "src/models/client.js~client.create",
    "class/src/models/client.js~Client.html#static-method-create",
    "src/models/client.js~Client.create",
    "method"
  ],
  [
    "src/models/client.js~client.get",
    "class/src/models/client.js~Client.html#static-method-get",
    "src/models/client.js~Client.get",
    "method"
  ],
  [
    "src/models/client.js~client.joinfamily",
    "class/src/models/client.js~Client.html#static-method-joinFamily",
    "src/models/client.js~Client.joinFamily",
    "method"
  ],
  [
    "src/models/client.js~client.joinorganization",
    "class/src/models/client.js~Client.html#static-method-joinOrganization",
    "src/models/client.js~Client.joinOrganization",
    "method"
  ],
  [
    "src/models/family.js",
    "file/src/models/family.js.html",
    "src/models/family.js",
    "file"
  ],
  [
    "src/models/family.js~family.create",
    "class/src/models/family.js~Family.html#static-method-create",
    "src/models/family.js~Family.create",
    "method"
  ],
  [
    "src/models/family.js~family.getmembers",
    "class/src/models/family.js~Family.html#static-method-getMembers",
    "src/models/family.js~Family.getMembers",
    "method"
  ],
  [
    "src/models/familyrequests.js",
    "file/src/models/familyrequests.js.html",
    "src/models/familyrequests.js",
    "file"
  ],
  [
    "src/models/familyrequests.js~familyrequests.create",
    "class/src/models/familyrequests.js~FamilyRequests.html#static-method-create",
    "src/models/familyrequests.js~FamilyRequests.create",
    "method"
  ],
  [
    "src/models/familyrequests.js~familyrequests.delete",
    "class/src/models/familyrequests.js~FamilyRequests.html#static-method-delete",
    "src/models/familyrequests.js~FamilyRequests.delete",
    "method"
  ],
  [
    "src/models/familyrequests.js~familyrequests.get",
    "class/src/models/familyrequests.js~FamilyRequests.html#static-method-get",
    "src/models/familyrequests.js~FamilyRequests.get",
    "method"
  ],
  [
    "src/models/models.js",
    "file/src/models/models.js.html",
    "src/models/models.js",
    "file"
  ],
  [
    "src/models/organization.js",
    "file/src/models/organization.js.html",
    "src/models/organization.js",
    "file"
  ],
  [
    "src/models/organization.js~organization.create",
    "class/src/models/organization.js~Organization.html#static-method-create",
    "src/models/organization.js~Organization.create",
    "method"
  ],
  [
    "src/models/organization.js~organization.get_all",
    "class/src/models/organization.js~Organization.html#static-method-get_all",
    "src/models/organization.js~Organization.get_all",
    "method"
  ],
  [
    "src/models/organization.js~organization.get_providers",
    "class/src/models/organization.js~Organization.html#static-method-get_providers",
    "src/models/organization.js~Organization.get_providers",
    "method"
  ],
  [
    "src/models/organizationrequests.js",
    "file/src/models/organizationrequests.js.html",
    "src/models/organizationrequests.js",
    "file"
  ],
  [
    "src/models/organizationrequests.js~organizationrequests.create",
    "class/src/models/organizationrequests.js~OrganizationRequests.html#static-method-create",
    "src/models/organizationrequests.js~OrganizationRequests.create",
    "method"
  ],
  [
    "src/models/organizationrequests.js~organizationrequests.delete",
    "class/src/models/organizationrequests.js~OrganizationRequests.html#static-method-delete",
    "src/models/organizationrequests.js~OrganizationRequests.delete",
    "method"
  ],
  [
    "src/models/organizationrequests.js~organizationrequests.get",
    "class/src/models/organizationrequests.js~OrganizationRequests.html#static-method-get",
    "src/models/organizationrequests.js~OrganizationRequests.get",
    "method"
  ],
  [
    "src/models/provider.js",
    "file/src/models/provider.js.html",
    "src/models/provider.js",
    "file"
  ],
  [
    "src/models/provider.js~provider.assignspecialization",
    "class/src/models/provider.js~Provider.html#static-method-assignSpecialization",
    "src/models/provider.js~Provider.assignSpecialization",
    "method"
  ],
  [
    "src/models/provider.js~provider.create",
    "class/src/models/provider.js~Provider.html#static-method-create",
    "src/models/provider.js~Provider.create",
    "method"
  ],
  [
    "src/models/provider.js~provider.get",
    "class/src/models/provider.js~Provider.html#static-method-get",
    "src/models/provider.js~Provider.get",
    "method"
  ],
  [
    "src/models/provider.js~provider.joinorganization",
    "class/src/models/provider.js~Provider.html#static-method-joinOrganization",
    "src/models/provider.js~Provider.joinOrganization",
    "method"
  ],
  [
    "src/models/user.js",
    "file/src/models/user.js.html",
    "src/models/user.js",
    "file"
  ],
  [
    "src/models/user.js~user.create",
    "class/src/models/user.js~User.html#static-method-create",
    "src/models/user.js~User.create",
    "method"
  ],
  [
    "src/routes/administrator.js",
    "file/src/routes/administrator.js.html",
    "src/routes/administrator.js",
    "file"
  ],
  [
    "src/routes/administrator.js~administratorroute#constructor",
    "class/src/routes/administrator.js~AdministratorRoute.html#instance-constructor-constructor",
    "src/routes/administrator.js~AdministratorRoute#constructor",
    "method"
  ],
  [
    "src/routes/administrator.js~administratorroute#router",
    "class/src/routes/administrator.js~AdministratorRoute.html#instance-method-router",
    "src/routes/administrator.js~AdministratorRoute#router",
    "method"
  ],
  [
    "src/routes/appointments.js",
    "file/src/routes/appointments.js.html",
    "src/routes/appointments.js",
    "file"
  ],
  [
    "src/routes/appointments.js~appointmentroute#constructor",
    "class/src/routes/appointments.js~AppointmentRoute.html#instance-constructor-constructor",
    "src/routes/appointments.js~AppointmentRoute#constructor",
    "method"
  ],
  [
    "src/routes/appointments.js~appointmentroute#router",
    "class/src/routes/appointments.js~AppointmentRoute.html#instance-method-router",
    "src/routes/appointments.js~AppointmentRoute#router",
    "method"
  ],
  [
    "src/routes/client.js",
    "file/src/routes/client.js.html",
    "src/routes/client.js",
    "file"
  ],
  [
    "src/routes/client.js~clientroute#constructor",
    "class/src/routes/client.js~ClientRoute.html#instance-constructor-constructor",
    "src/routes/client.js~ClientRoute#constructor",
    "method"
  ],
  [
    "src/routes/client.js~clientroute#router",
    "class/src/routes/client.js~ClientRoute.html#instance-method-router",
    "src/routes/client.js~ClientRoute#router",
    "method"
  ],
  [
    "src/routes/family.js",
    "file/src/routes/family.js.html",
    "src/routes/family.js",
    "file"
  ],
  [
    "src/routes/family.js~familyroute#constructor",
    "class/src/routes/family.js~FamilyRoute.html#instance-constructor-constructor",
    "src/routes/family.js~FamilyRoute#constructor",
    "method"
  ],
  [
    "src/routes/family.js~familyroute#router",
    "class/src/routes/family.js~FamilyRoute.html#instance-method-router",
    "src/routes/family.js~FamilyRoute#router",
    "method"
  ],
  [
    "src/routes/file.js",
    "file/src/routes/file.js.html",
    "src/routes/file.js",
    "file"
  ],
  [
    "src/routes/file.js~fileroute#constructor",
    "class/src/routes/file.js~FileRoute.html#instance-constructor-constructor",
    "src/routes/file.js~FileRoute#constructor",
    "method"
  ],
  [
    "src/routes/file.js~fileroute#router",
    "class/src/routes/file.js~FileRoute.html#instance-method-router",
    "src/routes/file.js~FileRoute#router",
    "method"
  ],
  [
    "src/routes/organization.js",
    "file/src/routes/organization.js.html",
    "src/routes/organization.js",
    "file"
  ],
  [
    "src/routes/organization.js~organizationroute#constructor",
    "class/src/routes/organization.js~OrganizationRoute.html#instance-constructor-constructor",
    "src/routes/organization.js~OrganizationRoute#constructor",
    "method"
  ],
  [
    "src/routes/organization.js~organizationroute#router",
    "class/src/routes/organization.js~OrganizationRoute.html#instance-method-router",
    "src/routes/organization.js~OrganizationRoute#router",
    "method"
  ],
  [
    "src/routes/provider.js",
    "file/src/routes/provider.js.html",
    "src/routes/provider.js",
    "file"
  ],
  [
    "src/routes/provider.js~providerroute#constructor",
    "class/src/routes/provider.js~ProviderRoute.html#instance-constructor-constructor",
    "src/routes/provider.js~ProviderRoute#constructor",
    "method"
  ],
  [
    "src/routes/provider.js~providerroute#router",
    "class/src/routes/provider.js~ProviderRoute.html#instance-method-router",
    "src/routes/provider.js~ProviderRoute#router",
    "method"
  ]
]